const QUESTIONS = [
  // Jídlo a pití
  'Mám rád/a sushi',
  'Nikdy jsem nejedl/a čínské jídlo',
  'Mám rád/a hlavolamy',
  'Piju kávu každý den',
  'Nikdy jsem nebyl/a opilý/á',
  'Mám rád/a pálivá jídla',
  'Jsem vegetarián/ka',
  'Nesnáším čokoládu',
  'Mám rád/a koriandr',
  'Vařím lépe než moje máma',
  'Nikdy jsem nejedl/a hmyz',
  'Mám rád/a syrové maso',
  'Piju čaj bez cukru',
  'Jím snídani každý den',
  'Mám rád/a ananas na pizze',
  'Nikdy jsem neměl/a kocovinu',
  'Mám rád/a kimchi',
  'Jím rychlé občerstvení max 1x týdně',
  'Mám rád/a hořkou čokoládu',
  'Nikdy jsem nejedl/a krevety',
  'Mám rád/a avokádo',
  'Piju alkohol jen při zvláštních příležitostech',
  'Mám rád/a kyselé okurky',
  'Nikdy jsem nejedl/a ústřice',
  'Mám rád/a tavený sýr',
  'Jím ovoce každý den',
  'Mám rád/a černou kávu',
  'Nikdy jsem nejedl/a klokaní maso',
  'Mám rád/a živé kultury v jogurtu',
  'Jím pomalu a vychutnávám si jídlo',
  'Mám rád/a párek v rohlíku',
  'Nikdy jsem nejedl/a zmrzlinu v zimě',
  'Mám rád/a kysané zelí',
  'Piji energetické nápoje',
  'Mám rád/a tatarák',
  'Nikdy jsem nejedl/a lososa',
  'Mám rád/a levelové věci v jídle',
  'Jím rád/a jídlo z food trucků',
  'Mám rád/a olivy',
  'Nikdy jsem neměl/a otravu jídlem',
  'Mám rád/a tofu',
  'Jím rád/a snídani k večeři',
  'Mám rád/a sýr s plísní',
  'Nikdy jsem nejedl/a granátové jablko',
  'Mám rád/a kokosovou vodu',
  'Piji pivo pravidelně',
  'Jím luštěniny aspoň 2x týdně',
  'Mám rád/a meloun se solí',
  'Nikdy jsem nejedl/a žabí stehýnka',
  'Mám rád/a matchu',
  'Mám rád/a bublinkový čaj',
  'Nikdy jsem nejedl/a kobylky',
  'Mám rád/a kynuté knedlíky',
  'Jím rád/a jídlo i studené',
  'Mám rád/a vinnou klobásu',
  'Nikdy jsem nezapálil/a jídlo při vaření',
  'Mám rád/a slané snídaně',
  'Piju mléko i po večeři',
  'Mám rád/a játra',
  'Nikdy jsem nejedl/a kaviár',
  'Mám rád/a mátovou příchuť',
  'Jím rád/a jídlo až druhý den',
  'Mám rád/a cibuli syrovou',
  'Nikdy jsem nezkoušel/a detox',
  'Mám rád/a špenát',
  'Jím rád/a mořské řasy',
  'Mám rád/a skořici ve všem',
  'Nikdy jsem nejedl/a langustu',
  'Mám rád/a burákové máslo',
  'Jím rád/a pizzu s ančovičkami',
  'Mám rád/a kozí sýr',
  'Nikdy jsem nejedl/a koninu',
  'Mám rád/a hořčici na všem',
  'Jím rád/a jídlo z mikrovlnky',
  'Mám rád/a červenou řepu',
  'Nikdy jsem neměl/a chuť na podivnou kombinaci jídel',
  'Mám rád/a tuňákový salát',
  'Jím rád/a těstoviny s kečupem',
  'Mám rád/a grilovaný hermelín',
  'Nikdy jsem nejedl/a sumce',
  'Mám rád/a kapary',
  'Jím rád/a jídlo z woku',
  'Mám rád/a dýňové latte',

  // Cestování
  'Byl/a jsem ve více než 5 zemích',
  'Už jsem letěl/a letadlem',
  'Nikdy jsem nebyl/a v kině',
  'Byl/a jsem v Asii',
  'Už jsem spal/a na letišti',
  'Cestoval/a jsem sám/sama',
  'Nikdy jsem necestoval/a mimo Evropu',
  'Mám rád/a roadtripy',
  'Už jsem bydlel/a v jiném městě než teď',
  'Byl/a jsem na Islandu',
  'Už jsem jel/a stopem',
  'Nikdy jsem nebyl/a v Praze',
  'Mám rád/a kempování',
  'Už jsem zmeškal/a letadlo',
  'Byl/a jsem v Africe',
  'Cestuju lehce - jen s příručním batohem',
  'Už jsem navštívil/a více než 20 zemí',
  'Nikdy jsem nebyl/a u moře',
  'Mám rád/a cestování vlakem',
  'Už jsem pracoval/a v zahraničí',
  'Byl/a jsem na Novém Zélandu',
  'Už jsem se ztratil/a v cizím městě',
  'Nikdy jsem nebyl/a v USA',
  'Mám rád/a hostelový styl cestování',
  'Už jsem cestoval/a déle než měsíc',
  'Byl/a jsem v Jižní Americe',
  'Už jsem plaval/a v oceánu',
  'Nikdy jsem nebyl/a na horách v zimě',
  'Mám rád/a cestování autobusem',
  'Už jsem letěl/a první třídou',
  'Byl/a jsem v Austrálii',
  'Už jsem se opil/a v cizí zemi',
  'Nikdy jsem nebyl/a na lodi',
  'Mám vytvořený bucket list destinací',
  'Už jsem navštívil/a stejné místo vícekrát jen proto, že se mi líbilo',
  'Nikdy jsem nestanoval/a',
  'Mám rád/a all inclusive dovolené',
  'Už jsem jel/a na kole po cizí zemi',
  'Byl/a jsem v Japonsku',
  'Už jsem potkal/a na cestách přátele na celý život',
  'Nikdy jsem nebyl/a na letišti sám/sama',
  'Mám rád/a noční vlaky',
  'Už jsem cestoval/a kvůli koncertu',
  'Byl/a jsem v poušti',
  'Už jsem spal/a pod širákem',
  'Nikdy jsem nebyl/a v muzeu v zahraničí',
  'Mám rád/a cestování s batůžkem',
  'Už jsem měl/a problémy s pasem na hranicích',
  'Byl/a jsem na plavbě lodí',
  'Už jsem jel/a autobusem přes noc',
  'Nikdy jsem nebyl/a v Římě',
  'Mám rád/a poznávání místní kuchyně při cestování',
  'Už jsem navštívil/a všechny kontinenty kromě Antarktidy',
  'Byl/a jsem v Severní Koreji',
  'Už jsem se zamiloval/a na cestách',
  'Nikdy jsem neletěl/a s Ryanair',
  'Mám vytvořenou mapu odlepených míst',
  'Už jsem byl/a v sauně v cizí zemi',
  'Byl/a jsem na Maledivách',
  'Už jsem řídil/a v cizí zemi',
  'Nikdy jsem nebyl/a v Londýně',
  'Mám rád/a pěší turistiku v horách',
  'Už jsem spal/a na nádraží',
  'Byl/a jsem v Paříži',
  'Už jsem cestoval/a s úplně cizím člověkem',
  'Nikdy jsem nejel/a vlakem přes noc',
  'Mám rád/a cestování nízkonákladovými aerolinkami',
  'Už jsem navštívil/a zemi jen kvůli jídlu',
  'Byl/a jsem v Egyptě',
  'Už jsem se koupal/a v ledovém jezeře',
  'Nikdy jsem nebyl/a v Německu',
  'Mám strach létat, ale létám',
  'Už jsem bydlel/a v cizině déle než 3 měsíce',
  'Byl/a jsem v Dubaji',
  'Už jsem platil/a úplatek na cestách',
  'Nikdy jsem nejel/a metrem v cizím městě',

  // Zvířata
  'Mám doma zvíře',
  'Bojím se pavouků',
  'Mám psa',
  'Nikdy jsem neměl/a domácí zvíře',
  'Mám rád/a kočky víc než psy',
  'Už jsem měl/a exotické domácí zvíře',
  'Bojím se hadů',
  'Mám rybičky',
  'Už jsem jezdil/a na koni',
  'Mám rád/a všechna zvířata',
  'Nikdy jsem nebyl/a na statku',
  'Mám alergii na srst',
  'Už jsem zachránil/a zvíře',
  'Mám rád/a plazy',
  'Bojím se psů',
  'Mám morče',
  'Už jsem měl/a křečka',
  'Mám rád/a ptáky',
  'Nikdy jsem nebyl/a v ZOO',
  'Mám rád/a hady jako mazlíčky',
  'Už jsem potkal/a medvěda v přírodě',
  'Mám strach z pavouků v bytě',
  'Už jsem choval/a slepice',
  'Mám králíka',
  'Bojím se myší',
  'Už jsem viděl/a velrybu naživo',
  'Mám rád/a exotické ptactvo',
  'Nikdy jsem se nebál/a žádného zvířete',
  'Už jsem krmil/a žirafu',
  'Mám rád/a včely',

  // Škola a práce
  'Mám rád/a matematiku',
  'Už jsem propadl/a u zkoušky',
  'Studoval/a jsem na vysoké škole',
  'Mám rád/a svou práci',
  'Už jsem dostal/a výpověď',
  'Byl/a jsem nejlepší žák ve třídě',
  'Už jsem podváděl/a u testu',
  'Mám rád/a chemické pokusy',
  'Už jsem změnil/a obor studia',
  'Pracuju v oboru, který jsem vystudoval/a',
  'Už jsem dostal/a padáka',
  'Měl/a jsem stejnou práci déle než 5 let',
  'Už jsem učil/a někoho ve škole',
  'Mám rád/a psaní slohových prací',
  'Už jsem sekundoval/a při zkoušce',
  'Měl/a jsem brigádu už na střední',
  'Už jsem chtěl/a skončit školu',
  'Mám rád/a fyziku',
  'Už jsem dělal/a práci, kterou jsem nenáviděl/a',
  'Byl/a jsem třídní šprt',
  'Už jsem vyhodil/a školu',
  'Mám rád/a učení se nových věcí',
  'Už jsem dostal/a pochvalu od šéfa',
  'Měl/a jsem vlastní firmu',
  'Už jsem spal/a v hodině',
  'Mám rád/a dějepis',
  'Už jsem pracoval/a v gastru',
  'Byl/a jsem předseda třídy',
  'Mám rád/a účetnictví',
  'Už jsem dělal/a bakalářku na poslední chvíli',
  'Pracuju v korporátu',
  'Už jsem falšoval/a podpis rodičů',
  'Mám rád/a angličtinu',
  'Už jsem dělal/a práci zadarmo',
  'Byl/a jsem šikanován/a ve škole',
  'Mám rád/a logické hádanky',
  'Už jsem dělal/a maturitu v cizím jazyce',
  'Mám rád/a svůj obor natolik, že čtu odborné články i ve volném čase',
  'Už jsem dostal/a vytknuto od profesora',
  'Měl/a jsem průměr pod 2.0',
  'Mám rád/a prezentování před lidmi',
  'Už jsem vyhodil/a spolužáka ze dveří',
  'Mám rád/a češtinu',
  'Už jsem pracoval/a v noci',
  'Byl/a jsem na stáži v zahraničí',
  'Mám rád/a programování',
  'Už jsem dělal/a zkoušku více než 3x',
  'Mám rád/a výzvy v práci',
  'Už jsem spal/a v práci',
  'Měl/a jsem individuální studijní plán',
  'Mám rád/a historii',
  'Už jsem pracoval/a v kavárně',
  'Byl/a jsem členem studentské organizace',
  'Mám rád/a geografii',
  'Už jsem požádal/a o zvýšení platu',
  'Už jsem přespal/a ve škole',
  'Mám rád/a biochemii',
  'Už jsem dělal/a práci, která neodpovídala mému vzdělání',
  'Byl/a jsem na prodloužené maturitě',
  'Mám rád/a tabulky a excel',
  'Už jsem propásl/a termín odevzdání',
  'Mám rád/a jazyky',
  'Už jsem pracoval/a v týmu, který se nesnášel',
  'Byl/a jsem na veletrhu pracovních příležitostí',
  'Mám rád/a robotiku',

  // Rodina a přátelé
  'Už jsem zapomněl/a na něčí narozeniny',
  'Mám více než 3 sourozence',
  'Bydlím s rodiči',
  'Už jsem se pohádal/a s nejlepším přítelem',
  'Mám blízký vztah se svou rodinou',
  'Už jsem slavil/a narozeniny sám/sama',
  'Mám sourozence, se kterým/ou si nerozumím',
  'Už jsem uspořádal/a rodinnou oslavu',
  'Nikdy jsem neviděl/a své prarodiče',
  'Mám rád/a své tchýni/tchána',
  'Už jsem uvažoval/a o přerušení kontaktu s rodinou',
  'Byl/a jsem na rodinné dovolené i jako dospělý/á',
  'Už jsem zapomněl/a na výročí rodičů',
  'Mám více než 10 bratranců a sestřenic',
  'Bydlím sám/sama',
  'Už jsem půjčil/a peníze příteli a nedostal/a je zpět',
  'Mám jednoho rodiče, kterému říkám křestním jménem',
  'Už jsem lhal/a rodičům o tom, kde jsem',
  'Mám rád/a rodinné večeře',
  'Už jsem se nepohodl/a s rodinou kvůli politice',
  'Mám blíž k mámě než k tátovi',
  'Už jsem bydlel/a se spolubydlícími, se kterými jsem nevycházel/a',
  'Mám okruh přátel, které znám od dětství',
  'Už jsem někoho zachránil/a před průšvihem',
  'Mám přátele, se kterými mluvím denně',
  'Už jsem se zamiloval/a do přítele/přítelkyně',
  'Nikdy jsem neměl/a nejlepšího přítele',
  'Už jsem řekl/a rodičům, že je miluju',
  'Mám rád/a oslavy s rodinou',
  'Už jsem zradil/a kamaráda',
  'Mám přátele ze všech koutů světa',

  // Záliby a koníčky
  'Mám rád/a karaoke',
  'Umím hrát na hudební nástroj',
  'Už jsem veřejně zpíval/a',
  'Mám rád/a čtení knih',
  'Už jsem napsal/a báseň',
  'Mám koníček, kterému se věnuju víc než 10 let',
  'Mám rád/a deskové hry',
  'Už jsem vymaloval/a podle čísel',
  'Mám rád/a křížovky',
  'Už jsem chodil/a do umělecké školy',
  'Sbírám něco',
  'Mám rád/a hru na kytaru',
  'Už jsem maloval/a obraz',
  'Mám rád/a videohry',
  'Už jsem četl/a knihu celý den',
  'Mám kreativní koníček (malování, psaní, hudba)',
  'Mám rád/a kutilství',
  'Už jsem dělal/a keramiku',
  'Mám rád/a fotografování',
  'Už jsem vyráběl/a šperky',
  'Mám rád/a pečení',
  'Už jsem pěstoval/a kaktusy',
  'Mám rád/a origami',
  'Už jsem dělal/a latinskoamerické tance',
  'Mám rád/a puzzle',
  'Už jsem psal/a deník',
  'Mám rád/a pletení',
  'Už jsem chodil/a do dramatického kroužku',
  'Mám rád/a kreslení',
  'Už jsem dělal/a kaligrafii',
  'Mám rád/a stolní tenis',
  'Už jsem vyráběl/a svíčky',
  'Mám rád/a hru na klavír',
  'Už jsem dělal/a scrapbooking',
  'Mám rád/a šachy',
  'Už jsem chodil/a do pěveckého sboru',
  'Mám rád/a rybaření',
  'Už jsem dělal/a youtubera/streamera',
  'Mám rád/a luštění sudoku',
  'Už jsem vlastnoručně vyrobil/a nábytek',
  'Mám rád/a jógu',
  'Už jsem dělal/a makramé',
  'Mám rád/a výrobu modelů',
  'Už jsem chodil/a do rybářského kroužku',
  'Mám rád/a astronomy a pozorování hvězd',
  'Už jsem psal/a povídky',
  'Mám rád/a turistiku',
  'Už jsem dělal/a digitální umění',

  // Strachy a fobie
  'Bojím se tmy',
  'Bojím se výšek',
  'Bojím se tmy v noci sám/sama doma',
  'Mám strach z neúspěchu',
  'Bojím se hadů',
  'Mám strach z budoucnosti',
  'Bojím se pavouků',
  'Mám strach z uzavřených prostor',
  'Bojím se hloubky',
  'Mám strach z odmítnutí',
  'Bojím se létat',
  'Mám strach ze tmy venku',
  'Bojím se klaunů',
  'Mám strach z výšek na horách',
  'Bojím se injekcí',
  'Mám strach ze samoty',
  'Bojím se bouřky',
  'Mám strach z veřejného vystupování',
  'Bojím se zubaře',
  'Mám strach z tmy v lese',
  'Bojím se vody',
  'Mám strach ze selhání před ostatními',
  'Bojím se blesků',
  'Mám strach z výtahů',
  'Bojím se tmy v cizím prostředí',
  'Mám strach z pavouků v posteli',
  'Bojím se přecházení mostů',
  'Mám strach ze vysokých budov',
  'Bojím se uzavřených výtahů',
  'Mám strach z mluvení před velkým publikem',
  'Bojím se bouřek venku',
  'Mám strach z neznámých lidí',

  // Zdraví a hygiena
  'Byl/a jsem někdy v nemocnici',
  'Mám rád/a chemické pokusy',
  'Už jsem měl/a zlomeninu',
  'Spím méně než 6 hodin denně',
  'Už jsem omdlel/a',
  'Daroval/a jsem krev',
  'Mám tetování',
  'Už jsem měl/a tříselnou kýlu',
  'Chodím na preventivní prohlídky pravidelně',
  'Už jsem měl/a zánět slepého střeva',
  'Mám rýmu aspoň 2x do roka',
  'Už jsem bral/a antibiotika zbytečně',
  'Cvičím pravidelně',
  'Už jsem prodělal/a operaci',
  'Mám chronické onemocnění',
  'Navštěvuji psychologa',
  'Už jsem měl/a otřes mozku',
  'Spím s otevřeným oknem',
  'Už jsem šel/šla k zubaři s bolavým zubem',
  'Beru vitamíny denně',
  'Už jsem měl/a alergickou reakci',
  'Dělám dechová cvičení',
  'Už jsem měl/a žloutenku',
  'Spím na zádech',
  'Už jsem se otravil/a jídlem',
  'Mám vysoký tlak',
  'Už jsem měl/a zápal plic',
  'Jím zdravě',
  'Už jsem utrpěl/a úraz sportem',
  'Medituji pravidelně',
  'Už jsem měl/a mononukleózu',
  'Mám problémy s páteří',
  'Už jsem byl/a na pohotovosti',
  'Piju dostatek vody každý den',
  'Už jsem měl/a migrénu',
  'Mám problémy se zrakem',
  'Už jsem držel/a dietu',
  'Spím minimálně 8 hodin',
  'Už jsem bral/a léky na spaní',
  'Mám rýmu vždycky na jaře',

  // Hudba, film, umění
  'Už jsem veřejně zpíval/a',
  'Mám rád/a horory',
  'Už jsem viděl/a stejný film více než 5x',
  'Hraju na hudební nástroj',
  'Mám rád/a klasickou hudbu',
  'Už jsem byl/a v opeře',
  'Mám rád/a jazz',
  'Už jsem četl/a knihu předlohu filmu',
  'Mám rád/a český rap',
  'Už jsem byl/a na rockovém koncertě',
  'Mám rád/a filmové maratony',
  'Už jsem plakal/a u filmu',
  'Mám rád/a metalfest',
  'Už jsem byl/a v kině sám/sama',
  'Mám rád/a seriály víc než filmy',
  'Už jsem usnul/a u filmu v kině',
  'Mám rád/a pop music',
  'Už jsem byl/a na festivalu',
  'Mám rád/a dokumenty',
  'Už jsem měl/a oblíbenou zpěvačku/zpěváka od dětství',
  'Mám rád/a techno',
  'Už jsem slyšel/a stejnou písničku 100x za sebou',
  'Mám rád/a artové filmy',
  'Už jsem chodil/a na hodiny hudebky',
  'Mám rád/a folk',
  'Už jsem byl/a na divadelním představení',
  'Mám rád/a netflix',
  'Už jsem se bál/a u hororu',
  'Mám rád/a indie hudbu',
  'Už jsem byl/a na baletu',
  'Mám rád/a sitcomy',
  'Už jsem byl/a na křtu desky',
  'Mám rád/a R&B',
  'Už jsem sledoval/a seriál celou noc',
  'Mám rád/a české filmy',
  'Už jsem byl/a na filmovém festivalu',
  'Mám rád/a soundtracky z filmů',
  'Už jsem byl/a v hledišti první řada na koncertě',
  'Mám rád/a reggae',
  'Už jsem poslouchal/a podcast',
  'Mám rád/a hip hop',
  'Už jsem byl/a v muzeu moderního umění',
  'Mám rád/a vánoční filmy i v létě',
  'Už jsem byl/a v galerii',
  'Mám rád/a punk rock',
  'Už jsem se učil/a hrát na kytaru',
  'Mám rád/a staré filmy z 80. let',
  'Už jsem byl/a v divadle na činohře',
  'Mám rád/a elektronickou hudbu',
  'Už jsem recitoval/a básničku před publikem',

  // Sport a pohyb
  'Umím plavat',
  'Umím jezdit na kole',
  'Mám rád/a plavání',
  'Už jsem byl/a na horolezecké stěně',
  'Mám rád/a běhání',
  'Už jsem se přihlásil/a na závod',
  'Mám rád/a tenis',
  'Už jsem jel/a na kole 50 km za den',
  'Mám rád/a fotbal',
  'Už jsem byl/a na maratonu (i jako divák)',
  'Umím lyžovat',
  'Už jsem dělal/a bojové umění',
  'Mám rád/a volejbal',
  'Už jsem dělal/a gymnastiku',
  'Umím bruslit',
  'Už jsem dělal/a atletiku',
  'Mám rád/a squashing',
  'Už jsem byl/a v posilovně jen jednou',
  'Umím skateboard',
  'Už jsem dělal/a tance',
  'Mám rád/a badminton',
  'Už jsem vyhrál/a sportovní medaili',
  'Umím snowboardovat',
  'Už jsem dělal/a parkour',
  'Mám rád/a jógu víc než posilovnu',
  'Už jsem plaval/a v oceánu',
  'Mám rád/a stolní fotbálek',
  'Už jsem byl/a na běžkách',
  'Umím jezdit na koni',
  'Už jsem dělal/a kanoistiku',
  'Mám rád/a šplhání po stromech',
  'Už jsem byl/a na lezeckém kurzu',
  'Mám rád/a cyklistiku',
  'Už jsem dělal/a potápění',
  'Umím házet frisbee daleko',
  'Už jsem byl/a na raftu',
  'Mám rád/a bouldering',
  'Umím udělat stojku',
  'Už jsem dělal/a akrobacii',
  'Mám rád/a tanec',

  // Technologie
  'Mám rád/a hlavolamy',
  'Už jsem programoval/a',
  'Mám účet na Twitteru',
  'Už jsem vytvořil/a webovou stránku',
  'Mám rád/a nové technologie',
  'Už jsem postavil/a počítač',
  'Mám chytré hodinky',
  'Už jsem dělal/a hru',
  'Mám rád/a AI technologie',
  'Už jsem používal/a ChatGPT',
  'Mám chytrou domácnost',
  'Už jsem napsal/a script',
  'Mám rád/a sociální sítě',
  'Už jsem dělal/a 3D tisk',
  'Mám více než 3 obrazovky u počítače',
  'Už jsem vytvořil/a mobilní aplikaci',
  'Mám rád/a robotický vysavač',
  'Už jsem zkoušel/a VR',
  'Mám rád/a retro hry',
  'Už jsem dělal/a androida',
  'Mám rád/a automaty na kávu',
  'Už jsem používal/a Linux',
  'Mám rád/a streamingové platformy',
  'Už jsem programoval/a v Pythonu',
  'Mám chytré světlo',
  'Už jsem dělal/a hackathon',
  'Mám rád/a nové gadgety',
  'Už jsem pracoval/a s databází',
  'Mám rád/a elektrické koloběžky',
  'Už jsem měl/a 3D model',
  'Mám nabíječku vždy u sebe',
  'Už jsem opravoval/a elektroniku',
  'Mám rád/a chytré telefony',
  'Už jsem dělal/a web scraping',
  'Mám rád/a vintage technologie',
  'Už jsem používal/a CLI',
  'Mám rád/a cloudové služby',
  'Už jsem tvořil/a projekt v týmu remote',
  'Mám rád/a mechanické klávesnice',
  'Už jsem skládal/a model ze stavebnice robotů',

  // Osobnost a povaha
  'Mám rád/a matematiku',
  'Mám rád/a noční život víc než denní',
  'Jsem ranní ptáče',
  'Mám rád/a nové výzvy',
  'Jsem spíše introvert',
  'Mám rád/a spontánní plány',
  'Jsem extrovert',
  'Mám rád/a rutinu',
  'Jsem perfekcionista',
  'Umím říct ne',
  'Jsem rád/a středem pozornosti',
  'Mám rád/a změny',
  'Jsem puntičkář',
  'Mám rád/a improvizaci',
  'Jsem optimista',
  'Dělám si starosti často',
  'Jsem spíše pesimista',
  'Mám rád/a plánování',
  'Jsem trpělivý/á',
  'Mám rád/a stabilitu',
  'Jsem chaotický/á',
  'Mám rád/a harmonii',
  'Jsem workoholik',
  'Mám rád/a minimalismus',
  'Jsem líný/á',
  'Mám rád/a luxus',
  'Jsem soutěživý/á',
  'Mám rád/a jednoduchost',
  'Jsem loajální za každou cenu',
  'Mám rád/a riziko',
  'Jsem upřímný/á až moc',
  'Mám rád/a konzistenci',
  'Jsem pragmatik',
  'Mám rád/a překvapení',
  'Jsem snílek',
  'Mám rád/a rozmanitost',
  'Jsem realista',
  'Mám rád/a tradice',
  'Jsem nervózní typ',
  'Mám rád/a svobodu',

  // Zážitky a zkušenosti
  'Už jsem něco ukradl/a',
  'Už jsem vyhrál/a nějakou soutěž',
  'Už jsem spal/a venku',
  'Už jsem potkal/a celebritu',
  'Mám řidičský průkaz',
  'Už jsem řídil/a auto',
  'Už jsem tančil/a na stole',
  'Už jsem dělal/a něco ilegálního',
  'Už jsem vyhrál/a v páce',
  'Už jsem řídil/a motorku',
  'Už jsem skákal/a padákem',
  'Už jsem se ztratil/a v lese',
  'Už jsem dělal/a stand-up comedy',
  'Už jsem vyhrál/a v loterii',
  'Už jsem řídil/a náklaďák',
  'Už jsem se koupal/a nahý/á',
  'Už jsem dělal/a bungee jumping',
  'Už jsem byl/a na policii',
  'Už jsem řídil/a traktor',
  'Už jsem přespal/a na pláži',
  'Už jsem dělal/a kravál v knihovně',
  'Už jsem vyhrál/a sázku',
  'Už jsem jel/a na motorce',
  'Už jsem plakal/a na veřejnosti',
  'Už jsem dělal/a scénu v restauraci',
  'Už jsem si vyměnil/a dárky v práci',
  'Už jsem jel/a v sanitce',
  'Už jsem prskal/a šampaňské jako na formulích',
  'Už jsem byl/a na svatbě jako svědek',
  'Už jsem jel/a taxíkem přes celé město',
  'Už jsem navštívil/a psychiatra',
  'Už jsem dělal/a karaoke na pódiu',
  'Už jsem jel/a autobusem špatným směrem',
  'Už jsem dělal/a přednášku',
  'Už jsem vyměnil/a pneumatiku',
  'Už jsem přespal/a na ubytovně',
  'Už jsem dělal/a ohňostroj',
  'Už jsem jel/a vrtulníkem',
  'Už jsem zachránil/a někomu život',
  'Už jsem pronajal/a auto',
  'Už jsem stál/a na vrcholu hory',
  'Už jsem zaspal/a důležitou událost',
  'Už jsem přeplaval/a řeku',
  'Už jsem lhal/a v životopisu',
  'Už jsem se schovával/a před někým',
  'Už jsem dělal/a hada na zdi',
  'Už jsem lezl/a po skalách',
  'Už jsem jedl/a jídlo z popelnice',
  'Už jsem potkal/a někoho slavného na ulici',
  'Už jsem dělal/a holubičku na veřejnosti',
  'Už jsem plakal/a štěstím',
  'Už jsem provozoval/a extrémní sport',
  'Už jsem zachránil/a zvíře z nouze',
  'Už jsem uvízl/a ve výtahu',
  'Už jsem uvařil/a jídlo pro 10+ lidí',
  'Už jsem přežil/a autonehodu',
  'Už jsem podal/a ruku někomu, koho jsem neměl/a rád/a',
  'Už jsem spal/a v lese sám/sama',
  'Už jsem dělal/a kouzelníka na dětské oslavě',
  'Už jsem jel/a na koni',
  'Už jsem ztratil/a telefon a našel/a ho',
  'Už jsem plakal/a z cibule tak, že jsem nemohl/a přestat',
  'Už jsem dělal/a pyrotechnika',
  'Už jsem byl/a na plese',
  'Už jsem měl/a autonehodu jako viník',
  'Už jsem přespal/a na nádraží',
  'Už jsem vyhrál/a první místo v něčem, na co jsem trénoval/a',
  'Už jsem dělal/a smradlavou bombu',
  'Už jsem byl/a na lovu',
  'Už jsem jel/a stopem s cizím člověkem',
  'Už jsem dělal/a dýňového strašáka',
  'Už jsem ochutnal/a jídlo, které mi nechutnalo, ale řekl/a jsem, že jo',
  'Už jsem stál/a na jevišti před stovkami lidí',
  'Už jsem se zranil/a při sportu a skončil/a v nemocnici',
  'Už jsem vylezl/a na střechu',
  'Už jsem se účastnil/a demonstrace',
  'Už jsem jel/a taxíkem s cizincem, se kterým jsem se skamarádil/a',
  'Už jsem se bál/a tak, že jsem brečel/a',
  'Už jsem dělal/a show pro přátele',
  'Už jsem spal/a na ulici',
  'Už jsem řídil/a loď',
  'Už jsem se schovával/a ve skříni při hře na schovávanou',
  'Už jsem dělal/a sám/a sobě překvapení',
  'Už jsem byl/a v psychiatrické léčebně na návštěvě',
  'Už jsem dělal/a optické klamy na fotkách',
  'Už jsem uvízl/a v lanovce',
  'Už jsem jel/a vlakem bez lístku',
  'Už jsem se pokusil/a o rekord v něčem',
  'Už jsem dělal/a kaskadérský kousek',
  'Už jsem vyhrál/a cenu v tombole',
  'Už jsem se koupal/a v ledové vodě',
  'Už jsem se toulal/a po městě celou noc',
  'Už jsem utekl/a z domu na pár hodin',
  'Už jsem měl/a den bez telefonu',
  'Už jsem ztratil/a klíče a musel/a volat zámečníka',
  'Už jsem navštívil/a hřbitov v noci',
  'Už jsem přečetl/a celou knihu za jeden den',

  // Společnost a kultura
  'Už jsem volil/a v komunálních volbách',
  'Mám rád/a politické debaty',
  'Už jsem podepsal/a petici',
  'Mám rád/a českou kulturu',
  'Už jsem byl/a na demonstraci',
  'Zajímám se o ekologii',
  'Mám rád/a divadlo',
  'Už jsem přispěl/a na charitu',
  'Mám rád/a prvomájové oslavy',
  'Už jsem se zapojil/a do dobrovolnictví',
  'Mám rád/a folklor',
  'Už jsem daroval/a oblečení na charitu',
  'Mám rád/a místní tradice',
  'Už jsem byl/a na pouti',
  'Zajímám se o historii své země',
  'Už jsem byl/a v kostele na mši',
  'Mám rád/a mezinárodní kuchyni',
  'Už jsem přispěl/a na crowdfunding',
  'Mám rád/a kulturní festivaly',
  'Už jsem navštívil/a památník',
  'Mám rád/a sousedské vztahy',
  'Už jsem třídil/a odpad i mimo domov',
  'Mám rád/a rozmanitost kultur',
  'Už jsem navštívil/a skanzen',
  'Zajímám se o práva zvířat',
  'Už jsem byl/a na hradě',
  'Mám rád/a české pohádky',
  'Už jsem pomáhal/a při povodních',
  'Mám rád/a sousedské posezení',
  'Už jsem byl/a na zámku',
  'Zajímám se o ochranu přírody',
  'Už jsem dělal/a sbírku pro potřebné',
  'Mám rád/a český folklór',
  'Už jsem byl/a na hřbitově o Dušičkách',
  'Mám rád/a vánoční trhy',
  'Už jsem se zúčastnil/a benefice',
  'Mám rád/a velikonoční tradice',
  'Už jsem propagoval/a udržitelnost',
  'Mám rád/a multikulturní akce',
  'Už jsem navštívil/a synagogu nebo mešitu',
  'Mám rád/a české sklářství',

  // Různé
  'Mám rád/a sushi',
  'Nikdy jsem nelhal/a příteli',
  'Umím plavat',
  'Mám tetování',
  'Mám rád/a horory',
  'Bojím se tmy',
  'Nikdy jsem neokusil/a alkohol',
  'Umím hrát na hudební nástroj',
  'Byl/a jsem někdy v nemocnici',
  'Mám rád/a hlavolamy',
  'Už jsem jel/a letadlem',
  'Mám doma zvíře',
  'Už jsem byl/a v kině',
  'Bojím se pavouků',
  'Už jsem vyhrál/a soutěž',
  'Mám rád/a zimu',
  'Už jsem spal/a venku',
  'Mám rád/a chemii',
  'Už jsem něco ukradl/a',
  'Mám rád/a hudbu',
  'Už jsem potkal/a celebritu',
  'Mám řidičák',
  'Už jsem řídil/a auto',
  'Mám rád/a čtení',
  'Už jsem brečel/a u filmu',
  'Mám rád/a cestování',
  'Už jsem lhal/a v životopise',
  'Mám rád/a vaření',
  'Už jsem zaspal/a do práce',
  'Mám rád/a psy víc než kočky',
  'Už jsem zapomněl/a klíče',
  'Mám rád/a noční oblohu',
  'Už jsem zkoušel/a drogy',
  'Mám rád/a thrillery',
  'Už jsem uvízl/a ve výtahu',
  'Mám rád/a sladké víc než slané',
  'Už jsem prskal/a šampaňské',
  'Mám rád/a podzim',
  'Už jsem dělal/a scénu',
  'Mám rád/a jaro',
  'Už jsem tančil/a na stole',
  'Mám rád/a léto',
  'Už jsem omdlel/a',
  'Mám rád/a zelenou barvu',
  'Už jsem dělal/a něco ilegálního',
  'Mám rád/a modrou barvu',
  'Už jsem lezl/a na skály',
  'Mám rád/a červenou barvu',
  'Už jsem se ztratil/a v lese',
  'Mám rád/a černou barvu',
  'Už jsem řídil/a motorku',
  'Mám rád/a bílou barvu',
  'Už jsem skákal/a padákem',
  'Mám rád/a žlutou barvu',
  'Už jsem plakal/a na veřejnosti',
  'Mám rád/a oranžovou barvu',
  'Už jsem přespal/a na pláži',
  'Mám rád/a fialovou barvu',
  'Už jsem řídil/a traktor',
  'Mám rád/a hnědou barvu',
  'Už jsem navštívil/a psychiatra',
  'Mám rád/a růžovou barvu',
  'Už jsem dělal/a karaoke na pódiu',
  'Mám rád/a šedou barvu',
  'Už jsem vyhrál/a v páce',
  'Mám rád/a tyrkysovou barvu',
  'Už jsem přežil/a autonehodu',
  'Už jsem dělal/a stand-up',
  'Už jsem dělal/a bungee jumping',
  'Mám rád/a pláž víc než hory',
  'Už jsem jel/a v sanitce',
  'Mám rád/a hory víc než pláž',
  'Už jsem byl/a na policii',
  'Mám rád/a město víc než vesnici',
  'Už jsem stál/a na vrcholu hory',
  'Mám rád/a vesnici víc než město',
  'Už jsem se koupal/a nahý/á',
  'Mám rád/a tanec',
  'Už jsem dělal/a hada na zdi',
  'Mám rád/a zpěv',
  'Už jsem vylezl/a na střechu',
  'Mám rád/a malování',
  'Už jsem přeplaval/a řeku',
  'Mám rád/a focení',
  'Už jsem jel/a vrtulníkem',
  'Mám rád/a psaní',
  'Už jsem dělal/a ohňostroj',
  'Mám rád/a sport',
  'Už jsem uvízl/a v lanovce',
  'Mám rád/a deskovky',
  'Už jsem vyhrál/a v loterii',
  'Mám rád/a videohry',
  'Už jsem dělal/a pyrotechnika',
  'Mám rád/a filmy',
  'Už jsem řídil/a loď',
  'Mám rád/a seriály',
  'Už jsem přečetl/a knihu za jednu noc',
  'Mám rád/a dokumenty',
  'Už jsem jel/a vlakem bez lístku',
  'Mám rád/a fantasy',
  'Už jsem prskal/a oheň',
  'Mám rád/a sci-fi',
  'Už jsem dělal/a akrobacii',
  'Mám rád/a komedie',
  'Už jsem zkusil/a hypnoterapii',
  'Mám rád/a drama',
  'Už jsem dělal/a kaskadéra',
  'Mám rád/a romantické filmy',
  'Už jsem spal/a na ubytovně',
  'Mám rád/a akční filmy',
  'Už jsem jel/a metrem v cizím městě',
  'Mám rád/a animované filmy',
  'Už jsem se ztratil/a v cizím městě',
  'Mám rád/a kriminální filmy',
  'Už jsem dělal/a něco, na co nejsem pyšný/á',
  'Mám rád/a historické filmy',
  'Už jsem se zamiloval/a na první pohled',
  'Mám rád/a muzikály',
  'Už jsem někomu zachránil/a život',
  'Mám rád/a české filmy',
  'Už jsem dýchal/a oxid uhličitý z hasičáku',
  'Už jsem byl/a na antarktické výpravě',
  'Mám rád/a komiksy',
  'Už jsem se převlékl/a za opačné pohlaví',
  'Už jsem dělal/a dabing',
  'Mám rád/a manga a anime',
  'Už jsem spal/a 24 hodin v kuse',
  'Už jsem strávil/a noc na hřbitově',
  'Mám rád/a krátké filmy',
  'Už jsem se probudil/a na neznámém místě',
  'Už jsem dělal/a kaskadéra v amatérském filmu',
  'Mám rád/a němé filmy',
  'Už jsem vařil/a jídlo z knížky',
  'Už jsem maloval/a graffiti (legálně)',
  'Už jsem se učil/a cizí jazyk jen z filmů',
  'Už jsem založil/a vlastní kapelu',
  'Už jsem slyšel/a písničku a brečel/a',
  'Už jsem zpíval/a na ulici',
  'Už jsem tancoval/a v dešti',
  'Už jsem ztratil/a pas v cizině',
  'Už jsem jedl/a 3 dny to samé jídlo',
  'Už jsem objednal/a jídlo v cizím jazyce a netušil/a co přijde',
  'Už jsem zapálil/a vánoční stromek',
  'Už jsem měl/a jednorožce na dortu',
  'Už jsem řídil/a pod vlivem',
  'Už jsem prorokoval/a budoucnost',
  'Už jsem se modlil/a za někoho',
  'Už jsem dělal/a exorcismus (jako žert)',
  'Už jsem odposlouchával/a cizí hovor',
  'Už jsem šmíroval/a sousedy',
  'Už jsem našel/a peníze na ulici',
  'Už jsem vyráběl/a domácí kino',
  'Už jsem stavěl/a bunkr',
  'Už jsem dělal/a leteckého modeláře',
  'Už jsem závodil/a na kole',
  'Už jsem chytil/a rybu rukama',
  'Už jsem pouštěl/a draka',
  'Už jsem dělal/a bubliny z mýdla',
  'Už jsem skládal/a origami',
  'Už jsem maloval/a na tričko',
  'Už jsem vyráběl/a náramky přátelství',
  'Už jsem dělal/a lampionový průvod',
  'Už jsem pouštěl/a lodičky z papíru',
  'Už jsem dělal/a písmomalbu',
  'Už jsem vytvářel/a koláž z časopisů',
  'Už jsem modeloval/a z hlíny',
  'Už jsem dělal/a vitráž',
  'Už jsem pěstoval/a bonsaj',
  'Už jsem choval/a mravence',
  'Už jsem dělal/a pokus s mentoskou a colou',
  'Už jsem stavěl/a sněhuláka',
  'Už jsem dělal/a andělíčka ve sněhu',
  'Už jsem vyřezával/a dýni',
  'Už jsem zdobil/a stromeček',

  // Zajímavé - odhalují osobnost
  'Nikdy jsem nikomu nezlomil/a srdce',
  'Už jsem někoho zachránil/a před utonutím',
  'Mám strach, že nebudu v životě dost úspěšný/á',
  'Už jsem plakal/a štěstím víc než smutkem',
  'Nikdy jsem nepodváděl/a v partnerském vztahu',
  'Mám pocit, že mě lidé často podceňují',
  'Už jsem odpustil/a něco, co mi přišlo neodpustitelné',
  'Bojím se, že skončím sám/sama',
  'Už jsem kvůli lásce udělal/a něco opravdu hloupého',
  'Věřím, že si každý tvoří vlastní štěstí',
  'Už jsem litoval/a, že jsem někomu řekl/a pravdu',
  'Mám tajný sen, o kterém nikdo neví',
  'Už jsem obětoval/a vlastní pohodlí pro někoho cizího',
  'Mám pocit, že mě moji přátéé neznají doopravdy',
  'Už jsem zalhal/a, abych ochránil/a něčí city',
  'Bojím se, že promarním svůj potenciál',
  'Už jsem záviděl/a někomu z přátel',
  'Dělám si starosti o budoucnost planety',
  'Už jsem se styděl/a za své rodiče',
  'Mám pocit, že se stále hledám',
  'Už jsem udělal/a něco, co by moje rodina neschvalovala',
  'Věřím na osud',
  'Už jsem obdivoval/a někoho natolik, že jsem chtěl/a být jako on/a',
  'Mám strach z odmítnutí',
  'Už jsem někomu zachránil/a den jen tím, že jsem ho vyslechl/a',
  'Mám tajnou dovednost, o které nikdo neví',
  'Už jsem zůstal/a v přátelství, které mi nesloužilo',
  'Bojím se, že nejsem dost dobrý/á',
  'Už jsem udělal/a něco, na co jsem pyšný/á, ale nikomu to neřeknu',
  'Mám pocit, že čas letí příliš rychle',
  'Už jsem se bál/a říct někomu, že ho/ji miluju',
  'Nikdy jsem nebyl/a zamilovaný/á',
  'Už jsem litoval/a, že jsem něco neudělal/a víc než toho, co jsem udělal/a',
  'Mám pocit, že si zasloužím víc, než mám',
  'Už jsem udělal/a něco jen proto, abych zapadl/a',
  'Bojím se, že zklamu lidi kolem sebe',
  'Mám problém říkat ne',
  'Už jsem zalhal/a v životopise a dostal/a díky tomu práci',
  'Mám pocit, že mě nikdo doopravdy nezná',
  'Už jsem se modlil/a o pomoc',
  'Věřím, že vše se děje z nějakého důvodu',
  'Už jsem udělal/a něco, co bych nikdy nepřiznal/a před rodinou',
  'Mám strach z toho, co si o mně myslí ostatní',
  'Už jsem se cítil/a osaměle v davu',
  'Mám pocit, že jsem v životě udělal/a zásadní chybu',
  'Už jsem se smál/a tak, že jsem brečel/a',
  'Bojím se, že nestíhám to, co se ode mě očekává',
  'Už jsem si přál/a mít jiný život',
  'Mám tajnou ambici, o které nikdo neví',
  'Věřím v život po smrti',
  'Už jsem obětoval/a přátelství kvůli lásce',
  'Mám pocit, že mě moje práce nenaplňuje',
  'Už jsem se cítil/a jako podvodník (impostor syndrome)',
  'Mám tajný plán pro případ apokalypsy',
  'Už jsem litoval/a, že jsem se narodil/a',
  'Už jsem udělal/a něco opravdu sobeckého',
  'Mám pocit, že jsem v životě nenašel/a své místo',
  'Už jsem chtěl/a zmizet a začít znovu někde jinde',
  'Nikdy jsem nepochyboval/a o svých schopnostech',
  'Už jsem někoho miloval/a víc než sebe',
  'Mám strach, že zůstanu pozadu',
  'Už jsem se styděl/a za něco, co jsem udělal/a v mládí',
  'Věřím, že každý má v sobě dobro',
  'Už jsem udělal/a něco nezákonného a nikdo o tom neví',
  'Mám pocit, že jsem v životě udělal/a správná rozhodnutí',
  'Už jsem někoho zachránil/a před špatným rozhodnutím',
  'Bojím se ticha',
  'Mám tajný deník nebo zápisky',
  'Už jsem zůstal/a v práci, kterou jsem nenáviděl/a, jen kvůli penězům',
  'Mám pocit, že se neustále srovnávám s ostatními',
  'Už jsem udělal/a něco, co šlo proti mému svědomí',
  'Věřím na znamení',
  'Už jsem někoho podržel/a v těžké chvíli',
  'Mám strach, že nebudu mít dost peněz na stáří',
  'Už jsem litoval/a, že jsem někomu pomohl/a',
  'Mám pocit, že žiju v bublině',
  'Už jsem zradil/a něčí důvěru',
  'Nikdy jsem nelitoval/a žádného svého rozhodnutí',
  'Už jsem se cítil/a v pasti',
  'Mám strach, že nejsem dostatečně milovaný/á',
  'Už jsem udělal/a něco jen pro ten pocit adrenalinu',
  'Věřím v lásku na celý život',
  'Už jsem obdivoval/a nepřítele',
  'Mám pocit, že si nezasloužím úspěch',
  'Už jsem se schválně vyhnul/a člověku, kterého jsem nechtěl/a potkat',
  'Bojím se, že promarním mládí',
  'Nikdy jsem nepochyboval/a o své hodnotě',
  'Už jsem se přestěhoval/a do jiného města kvůli novému začátku',
  'Mám strach, že mě někdo odhalí',
  'Už jsem zalhal/a, abych se vyhnul/a konfliktu',
  'Věřím na chemii mezi lidmi',
  'Už jsem udělal/a první krok ve vztahu',
  'Mám pocit, že jsem v životě nezažil/a dost dobrodružství',
  'Už jsem někoho zachránil/a před vlastní hloupostí',
  'Bojím se, že budu litovat věcí, které jsem neudělal/a',
  'Nikdy jsem se nezamiloval/a na první pohled',
  'Už jsem se cítil/a neviditelný/á',
  'Mám tajnou vášeň, o které nikdo neví',
  'Už jsem obětoval/a své sny pro někoho jiného',
  'Věřím, že všechno zlé je pro něco dobré',
  'Už jsem lhal/a o svém věku',
  'Mám strach, že nemám kontrolu nad svým životem',
  'Už jsem se vzdal/a něčeho důležitého, abych udělal/a radost druhým',
  'Nikdy jsem nepochyboval/a o tom, že budu šťastný/á',
  'Už jsem se probudil/a a nevěděl/a, kde jsem',
  'Mám pocit, že mě lidé využívají',
  'Už jsem udělal/a něco, na co vzpomínám s hrdostí',
  'Bojím se zklamat sám/sama sebe',
  'Už jsem obdivoval/a někoho, kdo si to nezasloužil',
  'Mám tajné místo, kam chodím přemýšlet',
  'Už jsem zalhal/a o svých pocitech',
  'Věřím, že si vesmír stojí za tím, co si přejeme',
  'Už jsem byl/a tak naštvaný/á, že jsem ztratil/a kontrolu',
  'Mám strach, že nikdy nenajdu opravdové štěstí',
  'Už jsem dala/dal výpověď bez plánu B',
  'Mám pocit, že jsem se v posledních letech nezměnil/a',
  'Už jsem se pokusil/a změnit kvůli někomu',
  'Bojím se, že mě historie nebude pamatovat',
  'Už jsem se styděl/a za svou profesi',
  'Mám tajný účet na sociální síti, o kterém nikdo neví',
  'Už jsem se smál/a v nevhodnou chvíli',
  'Věřím na intuici víc než na logiku',
  'Už jsem někoho políbil/a a hned toho litoval/a',
  'Mám strach z budoucnosti lidstva',
  'Už jsem si připadal/a jako nejhorší člověk na světě',
  'Nikdy jsem nepochyboval/a o svém vzhledu',
  'Už jsem se bál/a být sám/sama se svými myšlenkami',
  'Mám pocit, že žiju pro očekávání ostatních',
  'Už jsem litoval/a, že jsem se narodil/a do této doby',
  'Bojím se, že nikdy nebudu mít dost',
  'Už jsem obětoval/a víkend jen proto, abych pomohl/a cizímu člověku',
  'Mám pocit, že se pořád někam ženu a nestojí to za to',
  'Už jsem udělal/a něco, co by mě překvapilo u někoho jiného',
  'Věřím, že každý má druhou šanci',
  'Už jsem se snažil/a být někým, kým nejsem',
  'Mám strach, že nestihnu vše, co chci v životě zažít',
  'Už jsem odpustil/a někomu, kdo si to nezasloužil',
  'Nikdy jsem nežárlil/a',
  'Už jsem se cítil/a nedoceněný/á',
  'Mám tajný koníček, za který bych se styděl/a',
  'Už jsem udělal/a něco bláznivého pro lásku',
  'Bojím se, že budu litovat, až budu starý/á',
  'Už jsem přemýšlel/a o smyslu života a nenašel/a odpověď',
  'Mám pocit, že jsem lepší člověk než většina lidí, které znám',
  'Už jsem zachránil/a někomu život, aniž by o tom věděl/a',
  'Věřím na šťastné konce',
  'Už jsem se schválně zranil/a, abych nemusel/a něco dělat',
  'Mám strach, že mě čeká průměrný život',
  'Už jsem vyhodil/a peníze za něco, co jsem nikdy nepoužil/a',
  'Nikdy jsem nepochyboval/a o svém partnerovi/partnerce',
  'Už jsem se bál/a, že mi dojde čas',
  'Mám pocit, že se neustále učím, ale nikdy nejsem dost dobrý/á',
  'Už jsem dala/dal šanci někomu, kdo si to nezasloužil',
  'Bojím se, že mě čeká samota',
  'Už jsem se styděl/a plakat před ostatními',
  'Mám pocit, že jsem v životě udělal/a dost pro to, abych byl/a šťastný/á',
  'Už jsem se zamiloval/a do někoho, koho jsem nikdy nepotkal/a osobně',
  'Věřím, že láska není pro každého',
  'Už jsem se cítil/a uvězněný/á ve vlastním těle',
  'Mám strach, že ztratím své blízké',
  'Už jsem obětoval/a svůj čas pro někoho, kdo by pro mě neudělal to samé',
  'Nikdy jsem nepochyboval/a o svém životním směru',
  'Už jsem se smál/a, když jsem měl/a plakat',
  'Mám pocit, že svět je nespravedlivý',
  'Už jsem udělal/a něco, co šlo proti mým zásadám',
  'Bojím se, že nikdy nebudu opravdu šťastný/á',
  'Už jsem se cítil/a jako selhání',
  'Mám tajnou superschopnost - umím vycítit náladu lidí',
  'Už jsem se snažil/a zapadnout a přišlo mi to vyčerpávající',
  'Věřím na náhody',
  'Už jsem někoho přesvědčil/a o něčem, co nebyla pravda',
  'Mám strach, že ve skutečnosti nikoho nezajímám',
  'Už jsem si přál/a, abych byl/a někým jiným',
  'Nikdy jsem nepochyboval/a o svých přátelích',
  'Už jsem udělal/a něco pro peníze, za co se stydím',
  'Mám pocit, že mě čeká něco velkého',
  'Už jsem zůstal/a v toxickém vztahu déle, než jsem měl/a',
  'Bojím se, že mi život uteče mezi prsty',
  'Už jsem se bál/a být sám/a sebou',
  'Mám pocit, že jsem v životě potkal/a ty správné lidi',
  'Už jsem obdivoval/a někoho z dálky, aniž by o tom věděl/a',
  'Věřím, že každý má své poslání',
  'Už jsem se cítil/a pod tlakem dělat rozhodnutí, které jsem nechtěl/a',
  'Mám strach ze změn',
  'Už jsem někoho zklamal/a a nikdy jsem si to neodpustil/a',
  'Nikdy jsem nepochyboval/a o tom, že budu mít skvělý život',
  'Už jsem se smál/a sám/a sobě v zrcadle',
  'Mám pocit, že jsem ve špatném filmu',
  'Už jsem udělal/a něco odvážného a nelituju toho',
  'Bojím se, že nezanechám žádnou stopu',
  'Už jsem se snažil/a být perfektní a vyhořel/a jsem',
  'Mám tajný sen mít vlastní firmu / být umělcem / cestovat',
  'Už jsem se cítil/a nepochopený/á',
  'Věřím, že nejdůležitější je být šťastný',
  'Už jsem dala/dal přednost logice před srdcem a litovala jsem',
  'Mám strach, že mi nikdo nerozumí',
  'Už jsem zachránil/a někoho před trapnou situací',
  'Nikdy jsem nelitoval/a, že jsem upřímný/á',
  'Už jsem se cítil/a jako outsider',
  'Mám pocit, že jsem v minulém životě byl/a někdo jiný',
  'Už jsem obětoval/a spánek pro práci/školu a vyplatilo se to',
  'Bojím se, že nezvládám tlak',
  'Už jsem si myslel/a, že někoho znám, a mýlil/a jsem se',
  'Mám tajný talent, který jsem nikdy nerozvíjel/a',
  'Už jsem udělal/a něco laskavého pro cizího člověka bez důvodu',
  'Věřím, že se štěstí točí v kruzích',
  'Už jsem se styděl/a za svůj původ',
  'Mám strach, že se nikdy nezlepším',
  'Už jsem si přál/a mít nadpřirozené schopnosti',
  'Nikdy jsem nepochyboval/a o svých morálních hodnotách',
  'Už jsem se bál/a, že někoho ztratím',
  'Mám pocit, že dělám v životě rozdíl',
  'Už jsem záviděl/a někomu jeho životní styl',
  'Bojím se, že se nikdy neusadím',
  'Už jsem udělal/a něco, co by moje mladší já neschvalovalo',
  'Mám strach, že mě čeká budoucnost plná zklamání',
  'Už jsem se modlil/a za zázrak',
  'Věřím, že nejlepší věci v životě jsou zadarmo',
  'Už jsem se cítil/a jako bych žil/a v cizím těle',
  'Mám pocit, že jsem ve svém životě udělal/a maximum',
  'Už jsem litoval/a, že jsem se neozval/a',
  'Nikdy jsem nepochyboval/a o tom, že jsem milovaný/á',
  'Už jsem se vydal/a na cestu bez mapy',
  'Mám strach, že nejsem dostatečně silný/á na to, co mě čeká',
  'Už jsem se snažil/a změnit svět',
  'Bojím se, že můj život nemá smysl',
  'Už jsem obdivoval/a někoho, kdo byl úplně jiný než já',
  'Mám pocit, že jsem v životě potkal/a anděla',
  'Už jsem odpustil/a sám/sama sobě',
  'Věřím, že každý rok bude lepší než ten předchozí',
  'Už jsem se cítil/a jako ve správný čas na správném místě',
  'Mám strach, že nikdy nepochopím sám/sama sebe',
  'Už jsem udělal/a něco, co nikdo nečekal',
  'Nikdy jsem nepochyboval/a o tom, že si zasloužím lásku',
  'Už jsem si povídal/a s cizím člověkem o životě',
  'Mám pocit, že jsem se narodil/a do špatné doby',
  'Už jsem někomu zachránil/a život, aniž bych použil/a ruce',
  'Bojím se, že mi dojde naděje',
  'Už jsem se smál/a přes slzy',
  'Mám tajný plán na důchod',
  'Už jsem se cítil/a vděčný/á za to, kdo jsem',
  'Věřím, že každý den je dar',
  'Už jsem se zamiloval/a do představy, ne do člověka',
  'Mám strach, že nejsem dost pro ty, které miluju',
]

module.exports = QUESTIONS
